### PR TITLE
Gear Joint Constraint

### PR DESCRIPTION
**Pull request by elmfrain**
## Gear Joint Constraint

Implemented Bullet's `btGearConstraint` in Java with the `GearJoint` class.

### Why I Added This

I am using this library to simulate a vehicle for a future project, and I am modifying it so it can be suited for that. The gear constraint is crucial to simulate the gearbox, axles, and differential. Also, since this feature is mentioned on the "Whats Missing" section, I took it as an opportunity to contribute.

### Demo

In my application, there is a block (called 'testGear') on top of the vehicle that is hinged to the chassis and gear constrained to the front right wheel. 

```java
PhysicsRigidBody testGear = vparts.get("testGear").body;
PhysicsRigidBody frWheel = vparts.get("frWheel").body;
		
GearJoint gearJoint = new GearJoint(frWheel, testGear, Vector3f.UNIT_Z, Vector3f.UNIT_Y, 1.0f);
space.add(gearJoint);
```

And here is the result:

[https://www.youtube.com/watch?v=rAgXH9XIMvE](https://www.youtube.com/watch?v=rAgXH9XIMvE)

### CODE REVIEW

**Comment by YanisBDF** [comment]
Hello, I saw that you create Minecraft Mods.

Are you planning to use this on a Minecraft project ?

**Comment by elmfrain** [comment]
Haha yeah! I would like to create an offroading kart that simulates the suspension of a real vehicle. It's a dream of mine since I started to learn to code.

**Comment by YanisBDF** [comment]
Ah great ! Good luck ! 

Do you have en email or a discord so we can chat ?

**Comment by elmfrain** [comment]
Yeah my email is elmfer10@gmail.com.

**Comment by stephengold** [comment]
@elmfrain: I appreciate your contribution and will study it soon.

In the future, contact me *before* writing code you plan to contribute. I'd hate to accidentally duplicate your efforts!

**Comment by elmfrain** [comment]
Sure thing! I'll let you know next time I plan to contribute another feature.

**Comment by stephengold** [comment]
@elmfrain: I'd like to request a couple changes, please:

1. The additions to ".gitignore" are unrelated to the new feature and should be backed out prior to integration.
2. Rather than validating vectors as having unit length, I prefer to validate them as non-zero. That way there's no arbitrary boundary (between unit vectors and non-unit vectors) at which roundoff errors crash the app.

What do you think?

**Comment by stephengold** [comment]
@elmfrain Thanks for your contribution to the project!

**Pull request merged**
